more graceful handling of missing pidfile, #1395

diff --git a/nodebb b/nodebb
--- a/nodebb
+++ b/nodebb
@@ -33,13 +33,25 @@ case "$1" in
 		;;
 
 	stop)
-		echo "Stopping NodeBB. Goodbye!";
-		kill $(cat pidfile);
+		pidExists;
+		if [ 0 -eq $? ];
+			then
+				echo "NodeBB is already stopped.";
+			else
+				echo "Stopping NodeBB. Goodbye!";
+				kill $(cat pidfile);
+		fi
 		;;
 
 	reload|restart)
-		echo "Restarting NodeBB.";
-		kill -1 $(cat pidfile);
+		pidExists;
+		if [ 0 -eq $? ];
+			then
+				echo "NodeBB could not be restarted, as a running instance could not be found.";
+			else
+				echo "Restarting NodeBB.";
+				kill -1 $(cat pidfile);
+		fi
 		;;
 
 	status)
